# Generated by Django 4.2.5 on 2023-09-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
